language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  global:
    - BOTO_CONFIG=/doesnotexist
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal
before_install: 
  #- sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  #- sudo apt -qq update
  - sudo apt-get install -y python-dev libgdal1h libgdal-dev gdal-bin python-gdal
  - export CFLAGS=$(gdal-config --cflags)
  - export
# command to install dependencies
install:
  - pip install pygdal==1.10.0
  - pip install -r requirements.txt coverage --no-install gdal
# command to run tests
script: coverage run unit_tests.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
