language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
env:
  global:
    - BOTO_CONFIG=/doesnotexist
before_install: 
  - sudo apt-get install -y libgdal1h libgdal-dev gdal-bin
# command to install dependencies
install:
  #- pip install pygdal==1.10.0
  #- wget https://protobuf.googlecode.com/files/protobuf-2.4.1.tar.gz
  #- tar -xzvf protobuf-2.4.1.tar.gz
  #- pushd protobuf-2.4.1 && ./configure --prefix=/usr && make && sudo make install && popd
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - sudo pip install --download GDAL
  - cd /tmp/pip_build_root/GDAL
  - sudo python setup.py build_ext --include-dirs=/usr/include/gdal
  - sudo pip install --no-download GDAL
  - pip install -r requirements.txt coverage
# command to run tests
script: coverage run unit_tests.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
