language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
before-install: 
  #- sudo apt-get install -y gdal-bin
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install gdal-bin libgdal-dev
  - gdal-config --version
# command to install dependencies
install:
  - pip install -r requirements.txt coverage
# command to run tests
script: coverage run unit_tests.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
